const dietDatabase = {
    breakfasts: [
        // EASY
        { name: "Зернистий сир (200г) + 1 яблуко", speed: "Easy", p: 26, f: 9, c: 22, kcal: 273 },
        { name: "Сендвіч: цільнозерновий + моцарела (50г)", speed: "Easy", p: 18, f: 12, c: 25, kcal: 280 },
        { name: "Протеїновий шейк (300мл) + банан", speed: "Easy", p: 30, f: 5, c: 40, kcal: 325 },
        { name: "Йогурт Skyr (200г) + лохина", speed: "Easy", p: 22, f: 1, c: 18, kcal: 169 },
        { name: "3 рисові хлібці з Рікотою (60г)", speed: "Easy", p: 10, f: 8, c: 30, kcal: 232 },
        { name: "Мигдаль (30г) + батончик PAC", speed: "Easy", p: 25, f: 18, c: 20, kcal: 342 },
        { name: "Хліб з висівками + паштет тунця (80г)", speed: "Easy", p: 22, f: 6, c: 25, kcal: 242 },
        { name: "Сир 5% (200г) з ягодами (100г)", speed: "Easy", p: 30, f: 7, c: 15, kcal: 243 },
        { name: "Ветчина індички (100г) + 2 хлібці", speed: "Easy", p: 20, f: 4, c: 20, kcal: 196 },
        { name: "Кеш'ю (20г) + сухофрукти + кефір", speed: "Easy", p: 12, f: 12, c: 40, kcal: 316 },
        { name: "Вівсянка швидка + 1 сосиска PAC", speed: "Easy", p: 16, f: 12, c: 35, kcal: 312 },
        { name: "Твердий сир (50г) + хлібці (3 шт)", speed: "Easy", p: 16, f: 15, c: 25, kcal: 299 },
        { name: "М’який сир 0% + паста арахісова", speed: "Easy", p: 34, f: 10, c: 8, kcal: 258 },
        { name: "Чиа-пудинг (заготовлений)", speed: "Easy", p: 10, f: 14, c: 25, kcal: 266 },
        // MEDIUM
        { name: "Омлет (3 яйця) з авокадо + тост", speed: "Medium", p: 25, f: 25, c: 35, kcal: 465 },
        { name: "Вівсяноблін з сиром (50г)", speed: "Medium", p: 28, f: 12, c: 40, kcal: 380 },
        { name: "Яєчня-глазунья (3 яйця) з томатами", speed: "Medium", p: 21, f: 18, c: 6, kcal: 270 },
        { name: "Лаваш з моцарелою на грилі", speed: "Medium", p: 24, f: 14, c: 30, kcal: 342 },
        { name: "Гарячий тост з яйцем та беконом", speed: "Medium", p: 18, f: 16, c: 25, kcal: 316 },
        { name: "Вівсянка на воді + 1 варене яйце", speed: "Medium", p: 14, f: 10, c: 40, kcal: 306 },
        { name: "Омлет з кабачками та 2 яйцями", speed: "Medium", p: 16, f: 14, c: 10, kcal: 230 },
        { name: "Панкейки вівсяні (3 шт)", speed: "Medium", p: 12, f: 8, c: 45, kcal: 300 },
        { name: "Сирний лаваш з зеленню (обсмажений)", speed: "Medium", p: 28, f: 10, c: 25, kcal: 302 },
        { name: "Бутерброд з авокадо та куркою", speed: "Medium", p: 32, f: 15, c: 25, kcal: 363 },
        { name: "Скрембл з тофу та грибами", speed: "Medium", p: 22, f: 15, c: 10, kcal: 263 },
        { name: "Запечене яблуко з сиром", speed: "Medium", p: 20, f: 6, c: 30, kcal: 254 },
        { name: "Омлет білковий з лососем (30г)", speed: "Medium", p: 26, f: 8, c: 4, kcal: 192 },
        // HARD
        { name: "Шакшука (2 яйця) з фетою", speed: "Hard", p: 24, f: 20, c: 20, kcal: 356 },
        { name: "Кіш з куркою та шпинатом", speed: "Hard", p: 35, f: 20, c: 30, kcal: 440 },
        { name: "Домашня гранола з йогуртом", speed: "Hard", p: 22, f: 20, c: 45, kcal: 448 },
        { name: "Сирна запіканка (250г) з манкою", speed: "Hard", p: 40, f: 12, c: 40, kcal: 428 },
        { name: "Полента з сиром та грибами", speed: "Hard", p: 14, f: 12, c: 50, kcal: 364 },
        { name: "Млинці цільнозернові з сиром", speed: "Hard", p: 20, f: 12, c: 55, kcal: 408 },
        { name: "Бургер PAC: цільнозерновий з куркою", speed: "Hard", p: 35, f: 15, c: 40, kcal: 435 },
        { name: "Пиріг зі шпинатом та фетою", speed: "Hard", p: 14, f: 22, c: 30, kcal: 374 },
        { name: "Картопляні зрази з м'ясом", speed: "Hard", p: 18, f: 14, c: 45, kcal: 378 },
        { name: "Вівсянка запечена з грушею", speed: "Hard", p: 12, f: 10, c: 55, kcal: 358 },
        { name: "Оладки з печінки + салат", speed: "Hard", p: 32, f: 14, c: 15, kcal: 314 },
        { name: "Пшоно з морепродуктами у вершках", speed: "Hard", p: 28, f: 18, c: 45, kcal: 454 },
        { name: "Тофу смажений з овочами", speed: "Hard", p: 24, f: 16, c: 15, kcal: 300 }
    ],
    lunches: [
        // EASY (14)
        { name: "Тунець (130г) у лаваші", speed: "Easy", p: 35, f: 8, c: 40, kcal: 372 },
        { name: "Салат з нутом та овочами", speed: "Easy", p: 15, f: 10, c: 45, kcal: 330 },
        { name: "Куряче філе + мікс салат", speed: "Easy", p: 40, f: 5, c: 5, kcal: 225 },
        { name: "Сендвіч з індичкою та сиром", speed: "Easy", p: 30, f: 12, c: 45, kcal: 408 },
        { name: "Сочевичний суп + грінка", speed: "Easy", p: 18, f: 4, c: 40, kcal: 268 },
        { name: "Булгур з готовою куркою (100г)", speed: "Easy", p: 35, f: 10, c: 50, kcal: 430 },
        { name: "Салат з кіноа та яйцем", speed: "Easy", p: 20, f: 12, c: 35, kcal: 328 },
        { name: "Рол з хумусом та овочами", speed: "Easy", p: 12, f: 15, c: 45, kcal: 363 },
        { name: "Парова сьомга + огірок", speed: "Easy", p: 22, f: 14, c: 2, kcal: 222 },
        { name: "Квасоля (200г) + хлібці", speed: "Easy", p: 14, f: 2, c: 45, kcal: 254 },
        { name: "Салат Нісуаз (з тунцем)", speed: "Easy", p: 28, f: 12, c: 10, kcal: 260 },
        { name: "Гаспачо (300мл)", speed: "Easy", p: 5, f: 8, c: 20, kcal: 172 },
        { name: "Тофу-гриль (150г)", speed: "Easy", p: 22, f: 12, c: 5, kcal: 216 },
        { name: "Кускус з овочами", speed: "Easy", p: 10, f: 4, c: 50, kcal: 276 },
        // MEDIUM (13)
        { name: "Куряча грудка (150г) + рис", speed: "Medium", p: 45, f: 7, c: 60, kcal: 483 },
        { name: "Яловичина + булгур (150г)", speed: "Medium", p: 38, f: 15, c: 50, kcal: 487 },
        { name: "Паста цільнозернова з індичкою", speed: "Medium", p: 35, f: 10, c: 65, kcal: 490 },
        { name: "Кіноа з креветками (100г)", speed: "Medium", p: 30, f: 8, c: 45, kcal: 372 },
        { name: "Борщ з яловичиною (100г)", speed: "Medium", p: 25, f: 10, c: 30, kcal: 310 },
        { name: "Стейк індички + картопля", speed: "Medium", p: 40, f: 12, c: 50, kcal: 468 },
        { name: "Різотто з грибами (250г)", speed: "Medium", p: 12, f: 14, c: 55, kcal: 394 },
        { name: "Гречка з печінкою у сметані", speed: "Medium", p: 32, f: 15, c: 45, kcal: 443 },
        { name: "Минтай запечений + спаржа", speed: "Medium", p: 35, f: 6, c: 12, kcal: 242 },
        { name: "Шашлик з курки + овочі гриль", speed: "Medium", p: 42, f: 10, c: 10, kcal: 298 },
        { name: "Суп-пюре з брокколі", speed: "Medium", p: 12, f: 14, c: 25, kcal: 274 },
        { name: "Омлет з куркою та грибами", speed: "Medium", p: 35, f: 22, c: 8, kcal: 370 },
        { name: "Сендвіч Клаб з яйцем", speed: "Medium", p: 32, f: 18, c: 40, kcal: 450 },
        // HARD (13)
        { name: "Лазанья з кабачків з фаршем", speed: "Hard", p: 40, f: 20, c: 15, kcal: 400 },
        { name: "Котлети з індички + гречка", speed: "Hard", p: 42, f: 18, c: 45, kcal: 510 },
        { name: "Рагу з кролика та овочі", speed: "Hard", p: 38, f: 12, c: 25, kcal: 360 },
        { name: "Плов з яловичиною (250г)", speed: "Hard", p: 30, f: 18, c: 65, kcal: 542 },
        { name: "Форель запечена + овочі", speed: "Hard", p: 35, f: 22, c: 15, kcal: 398 },
        { name: "Тефтелі в томаті + паста", speed: "Hard", p: 36, f: 25, c: 40, kcal: 529 },
        { name: "Мусака з баклажанів", speed: "Hard", p: 35, f: 28, c: 20, kcal: 472 },
        { name: "Свиняча вирізка + рис", speed: "Hard", p: 40, f: 20, c: 55, kcal: 560 },
        { name: "Перці фаршировані (2 шт)", speed: "Hard", p: 28, f: 18, c: 35, kcal: 414 },
        { name: "Голубці з яловичиною (3 шт)", speed: "Hard", p: 30, f: 15, c: 40, kcal: 415 },
        { name: "Чахохбілі з куркою (200г)", speed: "Hard", p: 38, f: 14, c: 15, kcal: 338 },
        { name: "Суп Рамен з куркою", speed: "Hard", p: 35, f: 12, c: 60, kcal: 488 },
        { name: "Рибний пиріг PAC (150г)", speed: "Hard", p: 28, f: 18, c: 45, kcal: 454 }
    ],
    dinners: [
        // EASY
        { name: "Сир 5% (200г) + кефір", speed: "Easy", p: 32, f: 8, c: 10, kcal: 240 },
        { name: "Протеїновий пудинг (200г)", speed: "Easy", p: 25, f: 4, c: 12, kcal: 184 },
        { name: "Салат з моцарелою та томатами", speed: "Easy", p: 18, f: 15, c: 5, kcal: 227 },
        { name: "2 Яйця варені + огірок", speed: "Easy", p: 14, f: 12, c: 4, kcal: 180 },
        { name: "Йогурт + мигдаль (20г)", speed: "Easy", p: 15, f: 18, c: 10, kcal: 262 },
        { name: "Тунець (100г) + салат", speed: "Easy", p: 25, f: 2, c: 5, kcal: 138 },
        { name: "Шинка індички + помідор", speed: "Easy", p: 18, f: 3, c: 4, kcal: 115 },
        { name: "Кефір + насіння льону", speed: "Easy", p: 10, f: 12, c: 15, kcal: 208 },
        { name: "Хумус + морквяні палички", speed: "Easy", p: 6, f: 10, c: 25, kcal: 214 },
        { name: "Креветки відварні (100г)", speed: "Easy", p: 22, f: 2, c: 1, kcal: 110 },
        { name: "Сардини в соку + хлібець", speed: "Easy", p: 20, f: 10, c: 12, kcal: 218 },
        { name: "Творог 0% з какао", speed: "Easy", p: 30, f: 1, c: 8, kcal: 161 },
        { name: "Протеїновий шейк на воді", speed: "Easy", p: 25, f: 1, c: 3, kcal: 121 },
        { name: "Сир косичка (50г)", speed: "Easy", p: 14, f: 12, c: 1, kcal: 168 },
        // MEDIUM
        { name: "Тріска на пару + брокколі", speed: "Medium", p: 35, f: 4, c: 10, kcal: 216 },
        { name: "Стегно курки + овочі", speed: "Medium", p: 32, f: 18, c: 8, kcal: 322 },
        { name: "Омлет з морепродуктами", speed: "Medium", p: 30, f: 12, c: 5, kcal: 248 },
        { name: "Печінка куряча тушкована", speed: "Medium", p: 28, f: 14, c: 15, kcal: 298 },
        { name: "Скумбрія запечена з лимоном", speed: "Medium", p: 25, f: 25, c: 2, kcal: 333 },
        { name: "Гриби з куркою (100г)", speed: "Medium", p: 34, f: 12, c: 10, kcal: 284 },
        { name: "Квасоля стручкова з яйцем", speed: "Medium", p: 15, f: 10, c: 15, kcal: 210 },
        { name: "Хек запечений + томати", speed: "Medium", p: 30, f: 5, c: 8, kcal: 197 },
        { name: "Курячі сердечка + овочі", speed: "Medium", p: 26, f: 16, c: 10, kcal: 288 },
        { name: "Салат з авокадо та яйцем", speed: "Medium", p: 10, f: 22, c: 8, kcal: 270 },
        { name: "Індичка-гриль + кабачок", speed: "Medium", p: 35, f: 8, c: 10, kcal: 252 },
        { name: "Сирники солоні з зеленню", speed: "Medium", p: 32, f: 12, c: 15, kcal: 296 },
        { name: "Котлети рибні на пару", speed: "Medium", p: 28, f: 8, c: 12, kcal: 232 },
        // HARD
        { name: "Рулет з індички з травами", speed: "Hard", p: 42, f: 15, c: 12, kcal: 351 },
        { name: "Рибне суфле запечене", speed: "Hard", p: 30, f: 20, c: 8, kcal: 332 },
        { name: "2 Перці фаршировані м'ясом", speed: "Hard", p: 28, f: 18, c: 15, kcal: 334 },
        { name: "Салат Цезар (ПП) з куркою", speed: "Hard", p: 35, f: 22, c: 10, kcal: 378 },
        { name: "Мідії в томатному соусі", speed: "Hard", p: 26, f: 10, c: 12, kcal: 242 },
        { name: "Баклажани запечені з фаршем", speed: "Hard", p: 28, f: 18, c: 15, kcal: 334 },
        { name: "Заливне з курки (200г)", speed: "Hard", p: 35, f: 5, c: 5, kcal: 205 },
        { name: "Стейк тунця + шпинат", speed: "Hard", p: 40, f: 12, c: 5, kcal: 288 },
        { name: "Кролик у вині з травами", speed: "Hard", p: 38, f: 10, c: 5, kcal: 262 },
        { name: "Судак запечений під сиром", speed: "Hard", p: 35, f: 15, c: 5, kcal: 295 },
        { name: "Запіканка з брокколі та індички", speed: "Hard", p: 32, f: 14, c: 12, kcal: 302 },
        { name: "Кальмари фаршировані сиром", speed: "Hard", p: 30, f: 18, c: 5, kcal: 302 },
        { name: "Рулет з яловичини з чорносливом", speed: "Hard", p: 36, f: 22, c: 15, kcal: 402 }
    ]
};
